[package]
name = "show"
version = "0.1.0"
authors = ["halo <kkangwfu@163.com>"]
edition = "2018"

[dependencies]
actix = { git = "https://github.com/actix/actix" }
actix-web = { git = "https://github.com/actix/actix-web" }
env_logger = "0.5"